---
title: "Milestone 2"
author: "Derek Chang"
date: "9/24/2020"
output: html_document
---
[Repo for Final Project](https://github.com/dschang116/Final-Project/tree/master)

[The Language of Emojis](https://linda-qin.shinyapps.io/gov1005-emojis/) has an
impressive original data collection process, gathering its data in emojis, which 
is atypical of projects I have encountered thus far. The word cloud for was very 
aesthetically pleasing, but having emojis displayed instead of words would have 
been better to express the data, given how many words there are. The Emoji 
Network is also very well done, but I wish the word identifications were 
displayed as emojis and all connected nodes' labels were shown whenever one
is clicked. I wish the graph showing how we express love was better organized,
especially since there is so much going on. The graphs of emojis use by 
different could be better organized. Overall, I wish there was more analysis
of the data, though its general presentation would very good.

[Payroll and Performance in Professional Sports](https://wkcook.shinyapps.io/payroll-and-performance/) did a great job
given the sheer amount of data that was scraped and organized. The overall
presentation is also well done and interactive. The graphs are clear and
organized, and the different breakdowns by league, year, and team are quite
effective. However, I believe there needs to be far more analysis in the key 
takeaway sections, perhaps a general summative section. 
